#pragma once
#pragma comment(lib,"AppFrame.lib")

#include <DxLib.h>
#include "GameBase.h"
#include "ResourceServer.h"
#include "ModeServer.h"
#include "ModeBaseRoot.h"
#include "Texture.h"
#include "Matrix44.h"
#include "Vector4.h"
#include "DxUtility.h"
#include "PathServer.h"
#include "Utility.h"
#include "StateServer.h"
#include "StateBaseRoot.h"
#include "SoundServer.h"
#include "InputManager.h"
#include "LoadJson.h"
#include "EffectBaseRoot.h"
#include "EffectServer.h"
#include "ObjectBaseRoot.h"
#include "ObjectServer.h"
